# Generated by Django 6.0.2 on 2026-03-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
